### ISSUE TITLE
Migrate to dragonfly

### ISSUE THREAD

**Issue by Sayykii** [YuuCorp/Yuuko#18]
Recently found [dragonfly](https://github.com/dragonflydb/dragonfly), which is basically an alternative to redis, and is very easy to self-host. Another thing, it also integrates with the redis api, for which we will need [node-redis](https://github.com/redis/node-redis).

A few reasons to migrate to it, would be the ability to easily self-host, and the performance boost(which we will greatly benefit from)

**Comment by Sayykii** [comment]
I'd suggest you guys take a look at it too. @TibixDev @crackheadakira

**Comment by TibixDev** [comment]
Looks like it makes our life a bit easier, while being also faster. I'd say merge it.
